### PR TITLE
feat: add context manager; updated README

### PR DESCRIPTION
**Pull request by jorgeajimenezl**
I just added a context manager for better readability while changing the way they create client requests, this way you can [improve performance](https://www.python-httpx.org/advanced/#more-efficient-usage-of-network-resources) when making multiple requests in a row. I also removed some repetitive parts of the README.
Thanks

### CODE REVIEW

**Review by lugodev — APPROVED** [review]

**Comment by lugodev** [comment]
@jorgeajimenezl thanks a lot for your contribution!

For me it's ok to be merged but let's ask the experts about their opinion.

@codeshard @leynier could you please review this PR? It's adding a context manager to improve performance.

**Review by leynier — APPROVED** [review]
I changed the target branch to `lugodev:feature/context-manager` because is necessary that this pull request be merged for can run tests with the correct API key and secret.

Also, I fixed some format errors in the `README.md` and `client.py` files.

**Comment by lugodev** [comment]
@leynier what about the tests? I see the tests are failing.

https://github.com/lugodev/qvapay-python/pull/10/checks?check_run_id=3549318893

Is this ready to merge?

**Comment by leynier** [comment]
> @leynier what about the tests? I see the tests are failing.
> 
> https://github.com/lugodev/qvapay-python/pull/10/checks?check_run_id=3549318893
> 
> Is this ready to merge?

That happens because of what I mentioned in these comments:

- https://github.com/lugodev/qvapay-python/pull/8#issuecomment-913153212
- https://github.com/lugodev/qvapay-python/pull/8#issuecomment-913247742
- https://github.com/lugodev/qvapay-python/pull/10#pullrequestreview-749603626

**Comment by lugodev** [comment]
I've re-run the tests and keep failing. Now I'm  on blackout, later I'll check in the computer. Maybe we need to rewrite the tests to merge this.

**Comment by leynier** [comment]
The problem is that the tests need access to the secrets of the repository where the `API ID` and `API SECRET` are located.

But when a Pull Request is made by an external contributor, GitHub blocks access to secrets to prevent malicious acts.

I am investigating how to attack this problem, I found something that I am not sure is the solution but it does not hurt to try.

The possible solution is to activate the **"Require approval for all outside collaborators"** option in the **"Fork pull request workflows from outside collaborators"** section in the **"Actions"** section of the repository settings.

**Comment by lugodev** [comment]
I've applied the changes you suggested. Now what, is this ready to be merged, even if tests fails?

**Comment by leynier** [comment]
> I've applied the changes you suggested. Now what, is this ready to be merged, even if tests fails?

I changed the target branch of the pull request to `feature/context-manager` for the purpose that it can be merged safely because the branch is not `main`.

If the tests fail after the merge, no problem, apply the necessary changes so that the tests run correctly and then merge to the main branch.

**Review by lugodev — APPROVED** [review]

**Pull request merged**
