### PR TITLE
Fix transaction model and other things

### PR DESCRIPTION
**Pull request by leynier**
# Changes

- change `UUID` by `str` in `remote_id` of `transaction` model
- change `url` of banner in `README.md`
- add commitizen dev dependency for generate `CHANGELOG.md`
- bump version to `0.1.0` (to `0.1.0` and not to `0.0.4` because of existing `breaking changes`)

### CODE REVIEW

**Comment by leynier** [comment]
@lugodev, can you run GitHub Action again? The problem seems to be that executing the GitHub Action when done from an external collaborator in a PR does not have access to the GitHub Action Secrets, which is logical, because that collaborator could steal them through a custom GitHub Action.

**Comment by leynier** [comment]
1. Go to the following link

> <https://github.com/lugodev/qvapay-python/actions/runs/1203148759>

2. Click en Re-run all jobs

> image

**Comment by lugodev** [comment]
@leynier IDK but tests keep failing.

https://github.com/lugodev/qvapay-python/runs/3519808331?check_suite_focus=true

image

**Comment by lugodev** [comment]
But le latest action has completed successfully.

https://github.com/lugodev/qvapay-python/actions/runs/1203266408

**Comment by leynier** [comment]
> @leynier IDK but tests keep failing.
> 
> https://github.com/lugodev/qvapay-python/runs/3519808331?check_suite_focus=true
> 
> image

If you look at the errors it is because it does not find the id and secret of the app and it is because it is running the GitHub Action in a PR of an external collaborator, when it runs directly in the repository it works fine.

**Comment by lugodev** [comment]
Published v0.1.0 :tada:

https://github.com/lugodev/qvapay-python/releases/tag/v0.1.0

**Pull request merged**
